2017-05-31 12:02:55,942 ERROR 33120 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 33120
hostname: xiaomo

2017-05-31 12:05:59,438 ERROR 37168 [-/127.0.0.1/-/24ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'log_uid' in 'where clause'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT COUNT(*) as total FROM data_user_bean_return WHERE log_uid='62'
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 37168
hostname: xiaomo

2017-05-31 12:06:35,528 ERROR 37380 [-/127.0.0.1/-/45ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT return_id,return_uid,return_beans,return_money,return_account_type,return_create_time,return_finish_time,return_status FROM data_user_bean_log  WHERE return_uid = '62' ORDER BY return_id DESC LIMIT 0,1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 37380
hostname: xiaomo

2017-05-31 12:09:12,314 ERROR 36920 [-/127.0.0.1/-/24ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT return_id,return_uid,return_beans,return_money,return_account_type,return_create_time,return_finish_time,return_status FROM data_user_bean_log  WHERE return_uid = 62 ORDER BY return_id DESC LIMIT 0,1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 36920
hostname: xiaomo

2017-05-31 12:09:13,732 ERROR 36920 [-/127.0.0.1/-/8ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT return_id,return_uid,return_beans,return_money,return_account_type,return_create_time,return_finish_time,return_status FROM data_user_bean_log  WHERE return_uid = 62 ORDER BY return_id DESC LIMIT 0,1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 36920
hostname: xiaomo

2017-05-31 13:59:41,150 ERROR 33120 nodejs.ClusterClientNoResponseError: client no response in 2256637ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:72:23)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 33120
hostname: xiaomo

2017-05-31 13:59:47,870 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 13:59:53,651 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:01,652 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:09,652 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:17,652 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:25,653 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:33,653 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:41,654 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:49,654 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:57,656 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:05,692 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:13,694 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:21,694 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:29,695 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:37,694 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:45,697 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:53,697 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:02:01,708 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:02:09,698 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:02:17,698 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 15:16:51,241 ERROR 33120 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 33120
hostname: xiaomo

2017-05-31 15:23:40,442 ERROR 47284 [-/127.0.0.1/-/51ms POST /api/myaccount/beanReturnDetail] nodejs.TypeError: (intermediate value).Format is not a function
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:102:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 47284
hostname: xiaomo

2017-05-31 15:24:39,598 ERROR 43744 [-/127.0.0.1/-/23ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'node-datetime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:102:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 43744
hostname: xiaomo

2017-05-31 15:29:48,968 ERROR 51032 [-/127.0.0.1/-/28ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'node-datetime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 51032
hostname: xiaomo

2017-05-31 15:30:14,826 ERROR 49448 [-/127.0.0.1/-/28ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'node-datetime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 49448
hostname: xiaomo

2017-05-31 15:32:02,856 ERROR 51104 [-/127.0.0.1/-/23ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 51104
hostname: xiaomo

2017-05-31 15:32:04,488 ERROR 51104 [-/127.0.0.1/-/7ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 51104
hostname: xiaomo

2017-05-31 15:34:46,036 ERROR 51116 [-/127.0.0.1/-/27ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 51116
hostname: xiaomo

2017-05-31 15:34:47,545 ERROR 51116 [-/127.0.0.1/-/8ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 51116
hostname: xiaomo

2017-05-31 15:38:21,902 ERROR 51116 [-/127.0.0.1/-/9ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 51116
hostname: xiaomo

2017-05-31 15:39:48,725 ERROR 50252 [-/127.0.0.1/-/26ms POST /api/myaccount/beanReturnDetail] nodejs.MODULE_NOT_FOUNDError: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at MyaccountController.beanReturnDetail (E:\nodejs\sumi-server\app\controller\myaccount.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
code: 'MODULE_NOT_FOUND'
name: 'MODULE_NOT_FOUNDError'
pid: 50252
hostname: xiaomo

2017-05-31 16:11:44,855 ERROR 54228 [-/192.168.16.25/-/79ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18507499394' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18507499394', '9df57280e02731568dd31daa682e6373', 'BfQ9', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_DUP_ENTRYError'
pid: 54228
hostname: xiaomo

2017-05-31 16:13:25,876 ERROR 54228 [-/192.168.16.25/-/48ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18507499394' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18507499394', 'faac8ecfa772e796931c40a39f2d6902', '0g2a', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_DUP_ENTRYError'
pid: 54228
hostname: xiaomo

2017-05-31 16:13:29,959 ERROR 54228 [-/192.168.16.25/-/52ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18507499394' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18507499394', 'dd037c50a9a63b6cab8f7cf66415d4a0', '3OZQ', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_DUP_ENTRYError'
pid: 54228
hostname: xiaomo

2017-05-31 16:18:16,958 ERROR 50144 [-/192.168.16.25/-/56ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18507499394' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18507499394', 'c4e3f9b72accd493a33f9d1c6f8ee6cc', '269G', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_DUP_ENTRYError'
pid: 50144
hostname: xiaomo

2017-05-31 16:20:13,049 ERROR 50144 [-/127.0.0.1/-/47ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', '49fc097d8eeab560db0129d1a4b3ad7e', 'WUVx', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 50144
hostname: xiaomo

2017-05-31 16:25:46,444 ERROR 50144 [-/192.168.16.25/-/49ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18507499394' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18507499394', 'bbd8044d2532336e7772b10913f2493c', 'hNje', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_DUP_ENTRYError'
pid: 50144
hostname: xiaomo

2017-05-31 16:28:10,301 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 16:28:38,379 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 16:28:40,275 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 16:29:26,522 ERROR 54712 [-/127.0.0.1/-/18ms POST /api/login/register] nodejs.TypeError: this.ctx.service.veCode.checkuser is not a function
    at LoginController.register (E:\nodejs\sumi-server\app\controller\login.js:17:51)
    at Object.classControllerMiddleware (E:\nodejs\sumi-server\node_modules\egg-core\lib\loader\mixin\controller.js:74:32)
    at classControllerMiddleware.next (<anonymous>)
    at Object.dispatch (E:\nodejs\sumi-server\node_modules\koa-router\lib\router.js:335:14)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at Object.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\nodejs\sumi-server\node_modules\co\index.js:118:63)
    at next (E:\nodejs\sumi-server\node_modules\co\index.js:99:29)

pid: 54712
hostname: xiaomo

2017-05-31 16:29:57,887 ERROR 55696 [-/127.0.0.1/-/25ms POST /api/login/register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'where clause'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT * FROM `data_user_bean_return` WHERE `user_name` = '18814188611' LIMIT 0, 1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 55696
hostname: xiaomo

2017-05-31 16:33:20,584 ERROR 56224 [-/127.0.0.1/-/64ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'c0f22f90df594215960c8ee75f7e168e', 'VOtS', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 56224
hostname: xiaomo

2017-05-31 16:35:16,861 ERROR 54560 [-/127.0.0.1/-/78ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'fcd19b371d2ea0f61c73c1b21c2bcfdf', 'Obiq', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 54560
hostname: xiaomo

2017-05-31 16:35:17,800 ERROR 54560 [-/127.0.0.1/-/58ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'b35b171980e79b22a90a5f52ceed282a', 'Jqkn', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 54560
hostname: xiaomo

2017-05-31 16:36:58,929 ERROR 55968 [-/127.0.0.1/-/63ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', '989dd3455da2746ae1309135dbba63f4', 'ewHY', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 55968
hostname: xiaomo

2017-05-31 16:37:33,620 ERROR 53552 [-/127.0.0.1/-/76ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', '513e4eeddf8e504ac343745b8b49b02c', 'DT2f', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 53552
hostname: xiaomo

2017-05-31 16:37:35,202 ERROR 53552 [-/127.0.0.1/-/45ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'bb405598d6e8d331eac1ad001a702d42', 'rgCF', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 53552
hostname: xiaomo

2017-05-31 16:37:36,059 ERROR 53552 [-/127.0.0.1/-/44ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', '70c120ecb3a9feb32df6a00dfd679176', 'p3Nj', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 53552
hostname: xiaomo

2017-05-31 16:37:36,426 ERROR 53552 [-/127.0.0.1/-/62ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', '27b80cd6801dbce0b187796b4956fce9', '8Xd4', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 53552
hostname: xiaomo

2017-05-31 16:37:36,610 ERROR 53552 [-/127.0.0.1/-/46ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'a40a45aa9aabc0d34544847eeeff3202', '7i0H', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 53552
hostname: xiaomo

2017-05-31 16:37:36,810 ERROR 53552 [-/127.0.0.1/-/45ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', '1251d30e848acddb620ebe095d3a9ff0', '3zHG', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 53552
hostname: xiaomo

2017-05-31 16:38:13,479 ERROR 55444 [-/127.0.0.1/-/65ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'b977ec9daaa52570dec75a98d9d728e9', 'BKv2', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 55444
hostname: xiaomo

2017-05-31 16:38:54,771 ERROR 55016 [-/127.0.0.1/-/104ms POST /api/login/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '18814188611' for key 'name'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: INSERT INTO `data_user`(`user_name`, `user_pwd`, `user_salt`, `user_reg_time`) VALUES('18814188611', 'ce7a5648b593a0a45ccb521baecf78e9', 'ZoRy', now())
code: 'ER_DUP_ENTRY'
errno: 1062
sqlState: '23000'
index: 0
name: 'ER_DUP_ENTRYError'
pid: 55016
hostname: xiaomo

2017-05-31 16:48:10,971 ERROR 55576 [-/127.0.0.1/-/60ms POST /api/user/chatRootList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_status' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT log_id,log_main_id,log_room_expire,room_title as log_title ,room_photo as log_photo ,room_hits as log_hits,return_status FROM data_user_bean_log left join data_room on (room_id=log_main_id) WHERE log_uid = 1 AND log_type='join_room' ORDER BY return_id DESC LIMIT 0,5
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 55576
hostname: xiaomo

2017-05-31 16:49:50,727 ERROR 56152 [-/127.0.0.1/-/45ms POST /api/user/chatRootList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'order clause'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT log_id,log_main_id,log_room_expire,room_title as log_title ,room_photo as log_photo ,room_hits as log_hits FROM data_user_bean_log left join data_room on (room_id=log_main_id) WHERE log_uid = 1 AND log_type='join_room' ORDER BY return_id DESC LIMIT 0,5
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 56152
hostname: xiaomo

2017-05-31 17:25:24,323 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 17:26:39,231 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 17:28:30,610 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 17:47:15,112 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 17:51:12,266 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 17:51:46,427 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 17:54:17,916 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 18:01:55,768 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 18:07:45,664 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 18:19:23,729 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-05-31 18:20:03,997 ERROR 50352 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 50352
hostname: xiaomo

2017-06-01 09:10:02,397 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 10:23:03,188 ERROR 16376 [-/127.0.0.1/-/25ms POST /api/news/list] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'time' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT news_id,news_title,news_intro,news_create_time,news_hits,DATE_FORMAT(time,'%d-%m %H:%i') FROM data_news WHERE news_show = '1' ORDER BY news_id DESC LIMIT 0 , 20
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 16376
hostname: xiaomo

2017-06-01 10:29:20,024 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 10:31:06,603 ERROR 17280 [-/127.0.0.1/-/118ms POST /api/ad/list] nodejs.TypeError: result2.set is not a function
    at AdController.list (E:\nodejs\sumi-server\app\controller\ad.js:9:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 17280
hostname: xiaomo

2017-06-01 10:33:18,860 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 10:38:58,962 ERROR 17672 [-/127.0.0.1/-/368ms POST /api/ad/list] nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;col" ...skip... "cript.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode=\"Off\"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode=\"On\"/&gt; 或 &lt;customErrors mode=\"RemoteOnly\"/&gt;。-->"), POST http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt= 500 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"sdk.entinfo.cn:8061:":1},"requests":{}})
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 02:39:50 GMT","content-length":"5159"}
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 02:39:50 GMT","content-length":"5159"}
    at JSON.parse (<anonymous>)
    at parseJSON (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:894:24)
    at E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:677:23
    at decodeContent (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'JSONResponseFormatError'
data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484469\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.18408\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->'
path: '/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt='
status: 500
headers: { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 02:39:50 GMT', 'content-length': '5159' }
res: { status: 500, statusCode: 500, headers:  { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 02:39:50 GMT', 'content-length': '5159' }, size: 5159, aborted: false, rt: 250, keepAliveSocket: false, data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484469\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.18408\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->', requestUrls: [ 'http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt=' ], timing: null, remoteAddress: '115.182.203.188', remotePort: 8061 }
pid: 17672
hostname: xiaomo

2017-06-01 10:39:56,514 ERROR 2488 [-/127.0.0.1/-/264ms POST /api/ad/list] nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;col" ...skip... "cript.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode=\"Off\"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode=\"On\"/&gt; 或 &lt;customErrors mode=\"RemoteOnly\"/&gt;。-->"), POST http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt= 500 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"sdk.entinfo.cn:8061:":1},"requests":{}})
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 02:40:47 GMT","content-length":"5159"}
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 02:40:47 GMT","content-length":"5159"}
    at JSON.parse (<anonymous>)
    at parseJSON (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:894:24)
    at E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:677:23
    at decodeContent (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'JSONResponseFormatError'
data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484469\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.18408\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->'
path: '/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt='
status: 500
headers: { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 02:40:47 GMT', 'content-length': '5159' }
res: { status: 500, statusCode: 500, headers:  { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 02:40:47 GMT', 'content-length': '5159' }, size: 5159, aborted: false, rt: 139, keepAliveSocket: false, data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484469\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.18408\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->', requestUrls: [ 'http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt=' ], timing: null, remoteAddress: '115.182.203.188', remotePort: 8061 }
pid: 2488
hostname: xiaomo

2017-06-01 10:40:14,532 ERROR 16676 [-/127.0.0.1/-/176ms POST /api/ad/list] nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;col" ...skip... "cript.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode=\"Off\"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode=\"On\"/&gt; 或 &lt;customErrors mode=\"RemoteOnly\"/&gt;。-->"), POST http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt= 500 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"sdk.entinfo.cn:8061:":1},"requests":{}})
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 02:41:05 GMT","content-length":"5159"}
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 02:41:05 GMT","content-length":"5159"}
    at JSON.parse (<anonymous>)
    at parseJSON (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:894:24)
    at E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:677:23
    at decodeContent (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'JSONResponseFormatError'
data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484469\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.18408\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->'
path: '/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt='
status: 500
headers: { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 02:41:05 GMT', 'content-length': '5159' }
res: { status: 500, statusCode: 500, headers:  { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 02:41:05 GMT', 'content-length': '5159' }, size: 5159, aborted: false, rt: 135, keepAliveSocket: false, data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484469\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.18408\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->', requestUrls: [ 'http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=1234566【速米科技】&ext=&stime=&rrid=&msgfmt=' ], timing: null, remoteAddress: '115.182.203.188', remotePort: 8061 }
pid: 16676
hostname: xiaomo

2017-06-01 11:05:52,777 ERROR 15660 [-/127.0.0.1/-/241ms GET /api/ad/create] nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;col" ...skip... "cript.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode=\"Off\"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode=\"On\"/&gt; 或 &lt;customErrors mode=\"RemoteOnly\"/&gt;。-->"), POST http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=123456【速米科技】&ext=&stime=&rrid=&msgfmt= 500 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"sdk.entinfo.cn:8061:":1},"requests":{}})
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 03:06:44 GMT","content-length":"5159"}
headers: {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/7.5","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","date":"Thu, 01 Jun 2017 03:06:44 GMT","content-length":"5159"}
    at JSON.parse (<anonymous>)
    at parseJSON (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:894:24)
    at E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:677:23
    at decodeContent (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\nodejs\sumi-server\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'JSONResponseFormatError'
data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484389\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.34237\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->'
path: '/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=123456【速米科技】&ext=&stime=&rrid=&msgfmt='
status: 500
headers: { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 03:06:44 GMT', 'content-length': '5159' }
res: { status: 500, statusCode: 500, headers:  { 'cache-control': 'private', 'content-type': 'text/html; charset=utf-8', server: 'Microsoft-IIS/7.5', 'x-aspnet-version': '4.0.30319', 'x-powered-by': 'ASP.NET', date: 'Thu, 01 Jun 2017 03:06:44 GMT', 'content-length': '5159' }, size: 5159, aborted: false, rt: 232, keepAliveSocket: false, data: '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</title>\r\n        <meta name="viewport" content="width=device-width" />\r\n        <style>\r\n         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor="white">\r\n\r\n            <span><H1>“/”应用程序中的服务器错误。<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。</i> </h2></span>\r\n\r\n            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n            <b> 说明: </b>执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。\r\n\r\n            <br><br>\r\n\r\n            <b> 异常详细信息: </b>System.InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。<br><br>\r\n\r\n            <b>源错误:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\n执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。</code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>堆栈跟踪:</b> <br><br>\r\n\r\n            <table width=100% bgcolor="#ffffcc">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[InvalidOperationException: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。]\r\n   System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods) +484389\r\n   System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript) +244\r\n   System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context) +102\r\n   System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +62\r\n   System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) +47\r\n   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +346\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155\r\n</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <hr width=100% size=1 color=silver>\r\n\r\n            <b>版本信息:</b>&nbsp;Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.0.30319.34237\r\n\r\n            </font>\r\n\r\n    </body>\r\n</html>\r\n<!-- \r\n[InvalidOperationException]: 仅在类定义上有 [ScriptService] 特性的 Web 服务才能从脚本中调用。\r\n   在 System.Web.Script.Services.WebServiceData..ctor(Type type, Boolean pageMethods)\r\n   在 System.Web.Script.Services.WebServiceData.GetWebServiceData(HttpContext context, String virtualPath, Boolean failIfNoData, Boolean pageMethods, Boolean inlineScript)\r\n   在 System.Web.Script.Services.RestHandler.CreateHandler(HttpContext context)\r\n   在 System.Web.Script.Services.RestHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)\r\n   在 System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\r\n--><!-- \r\n此错误页可能包含敏感信息，因为 ASP.NET 通过 &lt;customErrors mode="Off"/&gt; 被配置为显示详细错误消息。请考虑在生产环境中使用 &lt;customErrors mode="On"/&gt; 或 &lt;customErrors mode="RemoteOnly"/&gt;。-->', requestUrls: [ 'http://sdk.entinfo.cn:8061/webservice.asmx/mdsmssend?sn=SDK-ZZB-010-00025&pwd=93C8CF517DC35B021D7B50ADCA564850&mobile=18814188612&content=123456【速米科技】&ext=&stime=&rrid=&msgfmt=' ], timing: null, remoteAddress: '115.182.203.188', remotePort: 8061 }
pid: 15660
hostname: xiaomo

2017-06-01 11:50:41,921 ERROR 19956 nodejs.ENOTFOUNDError: getaddrinfo ENOTFOUND http://sdk.entinfo.cn:8061 http://sdk.entinfo.cn:8061:80 (uncaughtException throw 1 times on pid:19956) (http://sdk.entinfo.cn:8061)
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
code: 'ENOTFOUND'
errno: 'ENOTFOUND'
syscall: 'getaddrinfo'
hostname: 'http://sdk.entinfo.cn:8061'
host: 'http://sdk.entinfo.cn:8061'
port: 80
name: 'ENOTFOUNDError'
pid: 19956
hostname: xiaomo

2017-06-01 11:50:43,693 ERROR 19956 nodejs.ENOTFOUNDError: getaddrinfo ENOTFOUND http://sdk.entinfo.cn:8061 http://sdk.entinfo.cn:8061:80 (uncaughtException throw 2 times on pid:19956) (http://sdk.entinfo.cn:8061)
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
code: 'ENOTFOUND'
errno: 'ENOTFOUND'
syscall: 'getaddrinfo'
hostname: 'http://sdk.entinfo.cn:8061'
host: 'http://sdk.entinfo.cn:8061'
port: 80
name: 'ENOTFOUNDError'
pid: 19956
hostname: xiaomo

2017-06-01 12:07:40,810 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:07:51,253 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:08:30,231 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:08:50,598 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:09:01,545 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:49:05,818 ERROR 9556 nodejs.ClusterClientNoResponseError: client no response in 531591ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:72:23)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 9556
hostname: xiaomo

2017-06-01 12:49:39,421 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:49:52,363 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 12:50:07,446 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 14:00:52,308 ERROR 9556 nodejs.ClusterClientNoResponseError: client no response in 567320ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:72:23)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 9556
hostname: xiaomo

2017-06-01 14:07:09,314 ERROR 24064 [-/127.0.0.1/-/2ms GET /ad/test/2/] nodejs.TypeError: Cannot match against 'undefined' or 'null'.
    at AdController.test (E:\nodejs\sumi-server\app\controller\ad.js:14:40)
    at Object.classControllerMiddleware (E:\nodejs\sumi-server\node_modules\egg-core\lib\loader\mixin\controller.js:74:32)
    at classControllerMiddleware.next (<anonymous>)
    at Object.dispatch (E:\nodejs\sumi-server\node_modules\koa-router\lib\router.js:335:14)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at Object.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\nodejs\sumi-server\node_modules\co\index.js:118:63)
    at next (E:\nodejs\sumi-server\node_modules\co\index.js:99:29)

pid: 24064
hostname: xiaomo

2017-06-01 15:02:07,131 ERROR 35000 [-/127.0.0.1/-/21ms POST /api/ad/create] nodejs.TypeError: this.curl is not a function
    at AdController.create (E:\nodejs\sumi-server\app\controller\ad.js:38:33)
    at create.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at Object.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\nodejs\sumi-server\node_modules\co\index.js:118:63)
    at next (E:\nodejs\sumi-server\node_modules\co\index.js:99:29)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:69:7)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at Object.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)

pid: 35000
hostname: xiaomo

2017-06-01 15:04:03,463 ERROR 36996 [-/127.0.0.1/-/18ms POST /api/ad/create] nodejs.TypeError: this.curl is not a function
    at AdController.create (E:\nodejs\sumi-server\app\controller\ad.js:38:33)
    at create.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at Object.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\nodejs\sumi-server\node_modules\co\index.js:118:63)
    at next (E:\nodejs\sumi-server\node_modules\co\index.js:99:29)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:69:7)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at Object.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)

pid: 36996
hostname: xiaomo

2017-06-01 15:12:52,535 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:35:45,275 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:36:01,085 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:36:44,757 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:37:11,155 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:37:17,003 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:39:00,162 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:39:08,016 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:41:37,208 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 15:47:24,581 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:00:47,657 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:01:09,233 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:15:21,399 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:16:27,328 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:21:36,737 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:27:09,550 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:27:15,192 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:39:01,977 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 16:42:37,508 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:05:58,234 ERROR 48552 [-/127.0.0.1/-/68ms POST /api/task/taskList] nodejs.TypeError: Cannot read property 'task_title' of undefined
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:64:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 48552
hostname: xiaomo

2017-06-01 17:08:39,492 ERROR 46364 [-/127.0.0.1/-/22ms POST /api/task/taskList] nodejs.TypeError: Cannot read property 'task_title' of undefined
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:64:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 46364
hostname: xiaomo

2017-06-01 17:19:45,085 ERROR 34608 [-/127.0.0.1/-/39ms POST /api/task/taskList] nodejs.TypeError: .iterator.next is not a function
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:66:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 34608
hostname: xiaomo

2017-06-01 17:20:04,149 ERROR 49240 [-/127.0.0.1/-/22ms POST /api/task/taskList] nodejs.TypeError: .iterator.next is not a function
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:66:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 49240
hostname: xiaomo

2017-06-01 17:20:06,195 ERROR 49240 [-/127.0.0.1/-/4ms POST /api/task/taskList] nodejs.TypeError: .iterator.next is not a function
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:66:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 49240
hostname: xiaomo

2017-06-01 17:26:51,261 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:29:40,381 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:29:50,366 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:39:33,206 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:39:48,610 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:40:55,483 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:41:08,859 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:43:17,639 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:47:29,368 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:47:42,438 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:48:51,372 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 17:50:00,399 ERROR 48408 [-/127.0.0.1/-/21ms POST /api/task/taskList] nodejs.SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:56:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 48408
hostname: xiaomo

2017-06-01 17:57:26,408 ERROR 51528 [-/127.0.0.1/-/22ms POST /api/task/taskList] nodejs.TypeError: .iterator.next is not a function
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:66:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 51528
hostname: xiaomo

2017-06-01 17:58:27,507 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 18:01:37,206 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 18:05:48,115 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 18:07:32,437 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 18:37:49,493 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 18:37:56,174 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 19:10:40,071 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 19:13:37,181 ERROR 57236 [-/127.0.0.1/-/43ms POST /api/task/taskList] nodejs.TypeError: Cannot read property 'key' of undefined
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:50:41)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 57236
hostname: xiaomo

2017-06-01 19:25:12,141 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 19:25:17,790 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 19:26:00,081 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 19:28:53,047 ERROR 43764 [-/127.0.0.1/-/10ms POST /api/task/taskList] nodejs.TypeError: Cannot create property 'task_status' on string 'sign'
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:40:29)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 43764
hostname: xiaomo

2017-06-01 19:40:51,628 ERROR 58632 [-/127.0.0.1/-/28ms POST /api/task/taskList] nodejs.TypeError: rs[value].push is not a function
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:40:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 58632
hostname: xiaomo

2017-06-01 19:42:14,200 ERROR 59188 [-/127.0.0.1/-/23ms POST /api/task/taskList] nodejs.SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at TaskService.taskList (E:\nodejs\sumi-server\app\service\task.js:34:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 59188
hostname: xiaomo

2017-06-01 19:48:34,924 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-01 20:05:25,741 ERROR 59356 [-/192.168.16.25/-/43ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:11:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
pid: 59356
hostname: xiaomo

2017-06-01 20:07:18,899 ERROR 60508 [-/192.168.16.25/-/54ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:11:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
pid: 60508
hostname: xiaomo

2017-06-01 20:07:38,630 ERROR 60508 [-/127.0.0.1/-/10ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:11:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 60508
hostname: xiaomo

2017-06-01 20:08:31,466 ERROR 59148 [-/127.0.0.1/-/57ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:12:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 59148
hostname: xiaomo

2017-06-01 20:13:33,648 ERROR 62364 [-/192.168.16.25/-/33ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:12:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
pid: 62364
hostname: xiaomo

2017-06-01 20:14:40,938 ERROR 58208 [-/192.168.16.25/-/16ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:12:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
pid: 58208
hostname: xiaomo

2017-06-01 20:14:54,045 ERROR 58208 [-/192.168.16.25/-/16ms POST /api/forum/boardDetail] nodejs.TypeError: Cannot read property 'user_follow_board' of null
    at ForumService.boardDetail (E:\nodejs\sumi-server\app\service\forum.js:12:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
pid: 58208
hostname: xiaomo

2017-06-01 20:36:36,071 ERROR 9556 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9556
hostname: xiaomo

2017-06-02 09:27:47,379 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 09:30:35,324 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 09:49:34,352 ERROR 13644 [-/127.0.0.1/-/22ms POST /api/task/finishTask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'task_mission1as' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT task_id,task_mission1as content FROM data_task WHERE task_uid = 62
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 13644
hostname: xiaomo

2017-06-02 10:00:46,944 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 10:04:00,133 ERROR 14600 [-/127.0.0.1/-/29ms POST /api/task/finishTask] nodejs.SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at TaskService.finishTask (E:\nodejs\sumi-server\app\service\task.js:54:28)
    at TaskController.finishTask (E:\nodejs\sumi-server\app\controller\task.js:51:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 14600
hostname: xiaomo

2017-06-02 10:06:52,032 ERROR 13824 [-/127.0.0.1/-/6ms POST /api/task/finishTask] nodejs.ReferenceError: status is not defined
    at TaskService.finishTask (E:\nodejs\sumi-server\app\service\task.js:55:39)
    at TaskController.finishTask (E:\nodejs\sumi-server\app\controller\task.js:51:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 13824
hostname: xiaomo

2017-06-02 10:45:25,372 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 10:50:21,206 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 10:56:36,221 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 11:11:45,049 ERROR 19344 [-/192.168.16.25/-/78ms POST /api/forum/addComment] nodejs.ER_BAD_NULL_ERRORError: ER_BAD_NULL_ERROR: Column 'reply_user_icon' cannot be null
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Protocol._enqueue (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at PoolConnection.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:208:25)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at PoolConnection.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at PoolConnection.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSConnection.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\connection.js:38:20)
    at RDSTransaction.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\transaction.js:45:26)
    at proto._query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `data_forum_reply`(`reply_board_id`, `reply_suject_id`, `reply_uid`, `reply_user`, `reply_nickname`, `reply_user_icon`, `reply_content`, `reply_create_time`) VALUES(1, '5', 50, '18507499394', 'mf', NULL, 'fghdfgh', now())
code: 'ER_BAD_NULL_ERROR'
errno: 1048
sqlState: '23000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_BAD_NULL_ERRORError'
pid: 19344
hostname: xiaomo

2017-06-02 11:30:17,078 ERROR 21844 nodejs.unhandledRejectionError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"key":"sign","status":"2","count":"0"} WHERE task_uid = 62' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: UPDATE data_task SET task_mission1={"key":"sign","status":"2","count":"0"} WHERE task_uid = 62
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
name: 'unhandledRejectionError'
pid: 21844
hostname: xiaomo

2017-06-02 11:43:13,047 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 11:45:10,094 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 11:46:19,650 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 11:47:56,771 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 11:51:07,850 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 12:04:54,765 ERROR 23220 [-/192.168.16.25/-/23ms POST /api/forum/commentdata] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DATE_FORMAT(reply_create_time,"%m-%d %H:%i") AS reply_create_time  FROM data_for' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT reply_id,reply_board_id,reply_user,reply_user_icon,reply_nickname,reply_content,reply_status,,DATE_FORMAT(reply_create_time,"%m-%d %H:%i") AS reply_create_time  FROM data_forum_reply WHERE reply_status = '1' AND  reply_suject_id= 3 ORDER BY reply_id DESC 
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_PARSE_ERRORError'
pid: 23220
hostname: xiaomo

2017-06-02 12:05:04,503 ERROR 21600 [-/192.168.16.25/-/13ms POST /api/forum/commentdata] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DATE_FORMAT(reply_create_time,"%m-%d %H:%i") AS reply_create_time  FROM data_for' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT reply_id,reply_board_id,reply_user,reply_user_icon,reply_nickname,reply_content,reply_status,,DATE_FORMAT(reply_create_time,"%m-%d %H:%i") AS reply_create_time  FROM data_forum_reply WHERE reply_status = '1' AND  reply_suject_id= 3 ORDER BY reply_id DESC 
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_PARSE_ERRORError'
pid: 21600
hostname: xiaomo

2017-06-02 12:05:15,235 ERROR 21600 [-/192.168.16.25/-/10ms POST /api/forum/commentdata] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DATE_FORMAT(reply_create_time,"%m-%d %H:%i") AS reply_create_time  FROM data_for' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT reply_id,reply_board_id,reply_user,reply_user_icon,reply_nickname,reply_content,reply_status,,DATE_FORMAT(reply_create_time,"%m-%d %H:%i") AS reply_create_time  FROM data_forum_reply WHERE reply_status = '1' AND  reply_suject_id= 3 ORDER BY reply_id DESC 
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000' }
name: 'ER_PARSE_ERRORError'
pid: 21600
hostname: xiaomo

2017-06-02 14:29:59,125 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 14:32:07,013 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 14:32:28,895 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 14:33:19,740 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 14:36:03,479 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 14:53:19,256 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 14:53:54,213 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 15:54:40,777 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 16:13:34,943 ERROR 43336 [-/127.0.0.1/-/37ms POST /api/forum/myBoardlist] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '5,1,4,2' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT board_id,board_title,board_description,board_stock_code,board_follow,board_hits,board_ishot,'1' as isfollow FROM data_forum_board where board_status='1' AND board_id in 5,1,4,2
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
name: 'ER_PARSE_ERRORError'
pid: 43336
hostname: xiaomo

2017-06-02 16:13:51,766 ERROR 43588 [-/127.0.0.1/-/29ms POST /api/forum/myBoardlist] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''5,1,4,2'' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT board_id,board_title,board_description,board_stock_code,board_follow,board_hits,board_ishot,'1' as isfollow FROM data_forum_board where board_status='1' AND board_id in '5,1,4,2'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
name: 'ER_PARSE_ERRORError'
pid: 43588
hostname: xiaomo

2017-06-02 16:14:17,676 ERROR 43856 [-/127.0.0.1/-/26ms POST /api/forum/myBoardlist] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''5,1,4,2'' at line 1
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT board_id,board_title,board_description,board_stock_code,board_follow,board_hits,board_ishot FROM data_forum_board where board_status='1' AND board_id in '5,1,4,2'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlState: '42000'
index: 0
name: 'ER_PARSE_ERRORError'
pid: 43856
hostname: xiaomo

2017-06-02 16:22:24,782 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 16:37:49,742 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 16:43:37,360 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 16:49:51,692 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 16:56:38,287 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 16:58:06,164 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:03:16,517 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:27:44,738 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:28:28,779 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:28:40,038 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:29:11,790 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:29:15,933 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:29:20,913 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:29:36,346 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:29:58,558 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:30:15,313 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:31:21,897 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:32:13,339 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:32:25,482 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:32:28,897 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:33:50,980 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:35:01,165 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:38:40,979 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:39:34,437 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

2017-06-02 17:39:39,295 ERROR 9212 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9212
hostname: xiaomo

